all:problem20

problem20:problem20.o bigint.o
	g++ -o problem20 problem20.o bigint.o

problem25:problem25.o bigint.o
	g++ -o problem25 problem25.o bigint.o

problem27:problem27.o primes.o
	g++ -o problem27 problem27.o primes.o

problem29:problem29.o bigint.o
	g++ -o problem29 problem29.o bigint.o

problem35:problem35.o primes.o
	g++ -o problem35 problem35.o primes.o

problem37:problem37.o primes.o
	g++ -o problem37 problem37.o primes.o

problem41:problem41.o primes.o pandigital.o
	g++ -o problem41 problem41.o primes.o pandigital.o

problem46:problem46.o primes.o
	g++ -o problem46 problem46.o primes.o

problem47:problem47.o primes.o
	g++ -o problem47 problem47.o primes.o

problem48:problem48.o bigint.o
	g++ -o problem48 problem48.o bigint.o

problem49:problem49.o primes.o
	g++ -o problem49 problem49.o primes.o

problem62:problem62.o bigint.o
	g++ -o problem62 problem62.o bigint.o

problem51:problem51.o primes.o
	g++ -o problem51 problem51.o primes.o
